services:
  db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_CONNECTION_PW}
      MYSQL_DATABASE: stockdb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    depends_on:
      - db
    environment:
      SQL_HOST: db
      SQL_CONNECTION_PW: ${SQL_CONNECTION_PW}
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
    ports:
      - "8502:8501"

volumes:
  db_data: